# Generated by Django 3.2.9 on 2022-12-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_alter_bankaccount_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'withdraw')], max_length=20),
        ),
    ]
