# Generated by Django 4.0.3 on 2022-12-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_alter_transactions_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('1', 'savings'), ('2', 'credit')], db_index=True, max_length=20),
        ),
    ]
