# Generated by Django 3.2.9 on 2022-12-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_alter_bankaccount_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('savings', 1), ('credit', 2)], db_index=True, max_length=20),
        ),
    ]
