# Generated by Django 3.2.9 on 2022-12-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_alter_bankaccount_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=20),
        ),
    ]
